version: '3.2'
services:
  www:
    build:
      context: ./docker/php-apache
    container_name: ${PROJECT_NAME}_www
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./code:/var/www
      - ./docker/php-apache/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php-apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro

  mysql:
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: ${PROJECT_NAME}_mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: ${PROJECT_NAME}_phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: ${PROJECT_NAME}_mailhog
    ports:
      - ${MAILHOG_SMPT_PORT}:1025
      - ${MAILHOG_WEB_PORT}:8025

  selenium_chrome:
    image: selenium/node-chrome:4.0.0-beta-1-20210215
    container_name: ${PROJECT_NAME}_selenium_chrome
    ports:
      - "6900:5900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
      - www

  selenium-hub:
    image: selenium/hub:4.0.0-beta-1-20210215
    container_name: ${PROJECT_NAME}_selenium-hub
    ports:
      - "${SELENIUM_HUB_PORT_1}:4442"
      - "${SELENIUM_HUB_PORT_2}:4443"
      - "${SELENIUM_HUB_PORT_3}:4444"
volumes:
  mysql-data:
